defaults: &defaults
    working_directory: ~/stealth_api
    docker:
      - image: circleci/ruby:2.5.0-browsers
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          BUNDLE_APP_CONFIG: ~/stealth_api/.bundle/config
          DB_HOST_NAME: 127.0.0.1
      - image: circleci/mysql:5.7.20
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: redis
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          REDIS_HOST: 127.0.0.1
          REDIS_URL: redis://127.0.0.1:6379

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/stealth_api
          paths:
            - ./*
  rspec:
    parallelism: 1
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/stealth_api
      - run:
          name: MySQL run check
          command: |
            java -version
#            sleep 5 && ps aux && wget --waitretry=5 --retry-connrefused -v http://localhost:9200/
      - run: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.1.tar.gz
      - run: tar -xvf elasticsearch-6.0.1.tar.gz
      - run: elasticsearch-6.0.1/bin/elasticsearch-plugin install analysis-kuromoji
      - run:
          command: elasticsearch-6.0.1/bin/elasticsearch
          background: true
      - run: sleep 10 && wget --waitretry=5 --retry-connrefused -v http://127.0.0.1:9200/
      - run: curl http://127.0.0.1:9200/
      - store_artifacts:
          path: artifacts/
      - store_test_results:
          path: rspec/
workflows:
  version: 2
  workflows:
    jobs:
      - build
      - rspec:
          requires:
            - build
#          filters:
#            branches:
#              ignore: /^sandbox.*|^master$|^staging$/
