defaults: &defaults
    working_directory: ~/stealth_api
    docker:
      - image: circleci/ruby:2.5.0-browsers
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          BUNDLE_APP_CONFIG: ~/stealth_api/.bundle/config
          DB_HOST_NAME: 127.0.0.1
      - image: circleci/mysql:5.7.20
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: redis
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          REDIS_HOST: 127.0.0.1
          REDIS_URL: redis://127.0.0.1:6379

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: stealth_api-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle 1.16.2
          command: gem install bundler -v 1.16.2
      - run:
          name: bundle install
          command: bundle install --jobs=4 --path=vendor/bundle
      - save_cache:
          key: stealth_api-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/stealth_api
          paths:
            - ./*
  rspec:
    parallelism: 2
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/stealth_api
      - restore_cache:
          key: v12-stealth_api-elasticsearch
      - run:
          name: elasticsearch install
          command: |
            wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.1.tar.gz && \
              tar -xvf elasticsearch-6.0.1.tar.gz && \
              if [ -z "`elasticsearch-6.0.1/bin/elasticsearch-plugin list | grep analysis-kuromoji`" ]; then \
              elasticsearch-6.0.1/bin/elasticsearch-plugin install analysis-kuromoji; fi
      - save_cache:
          key: v12-stealth_api-elasticsearch
          paths:
            - ./elasticsearch-6.0.1
      - run:
          name: start elasticsearch
          command: |
            pwd;
            elasticsearch-6.0.1/bin/elasticsearch -d
      - run:
          name: wait elasticsearch
          command: |
            sleep 10 && wget --waitretry=5 --retry-connrefused -v http://127.0.0.1:9200/
      - run:
          name: database create
          command: bundle exec rake db:create db:schema:load
          environment:
            RAILS_ENV: test
      - run:
          name: run test
          command: |
            bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out rspec/rspec.xml \
              --require spec_helper spec \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          environment:
            RAILS_ENV: test
      - store_artifacts:
          path: artifacts/
      - store_test_results:
          path: rspec/
workflows:
  version: 2
  workflows:
    jobs:
      - build
      - rspec:
          requires:
            - build
#          filters:
#            branches:
#              ignore: /^sandbox.*|^master$|^staging$/
