defaults: &defaults
    working_directory: ~/stealth_api
    docker:
      - image: circleci/ruby:2.5.0
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          BUNDLE_APP_CONFIG: ~/stealth_api/.bundle/config
          DB_HOST_NAME: 127.0.0.1
      - image: circleci/mysql:5.7.20
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
      - image: redis
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          REDIS_HOST: 127.0.0.1
          REDIS_URL: redis://127.0.0.1:6379
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
        command: elasticsearch-plugin install analysis-kuromoji
        name: elasticsearch
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          http.host: '0.0.0.0'
          http.port: 9200
          xpack.security.enabled: false
          xpack.monitoring.enabled: false
          xpack.watcher.enabled: false
          xpack.graph.enabled: false
          xpack.ml.enabled: false
          ES_JAVA_OPTS: '-Xms256m -Xmx256m'

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/stealth_api
          paths:
            - ./*
  rspec:
    parallelism: 1
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/stealth_api
      - run:
          name: MySQL run check
          command: |
            curl http://localhost:9200/

#      - run:
#          name: MySQL run check
#          command: |
#            for i in 5
#            do
#              mysql -h 127.0.0.1 -u root -e 'show databases' || (sleep 5; false) && break
#            done
#      - run:
#          name: database create
#          command: bundle exec rake db:create db:schema:load
#          environment:
#            RAILS_ENV: test
#      - run:
#          name: run test
#          command: |
#            bundle exec rspec --profile 20 \
#              --out rspec/rspec.xml \
#              --color \
#              --require spec_helper spec \
#              --format progress \
#              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
#          environment:
#            RAILS_ENV: test
      - store_artifacts:
          path: artifacts/
      - store_test_results:
          path: rspec/
workflows:
  version: 2
  workflows:
    jobs:
      - build
      - rspec:
          requires:
            - build
#          filters:
#            branches:
#              ignore: /^sandbox.*|^master$|^staging$/
